### ISSUE TITLE
About the args parsing problem, trouble you have time to solve, thank you!

### ISSUE THREAD

**Issue by chenchenver** [Jakel21/vehicle-ReID-baseline#4]
Hello, I have encountered the problem in figure 1。
![QQ图片20190816175201](https://user-images.githubusercontent.com/44572100/63159999-44290880-c04f-11e9-8536-7880c7b6730a.png)

may I ask what the correct format should be in figure 2?
![QQ图片20190816175125](https://user-images.githubusercontent.com/44572100/63160007-4a1ee980-c04f-11e9-8577-3d2c88cd94b4.png)

**Comment by Jakel21** [comment]
> Hello, I have encountered the problem in figure 1。
> ![QQ图片20190816175201](https://user-images.githubusercontent.com/44572100/63159999-44290880-c04f-11e9-8536-7880c7b6730a.png)
> 
> may I ask what the correct format should be in figure 2?
> ![QQ图片20190816175125](https://user-images.githubusercontent.com/44572100/63160007-4a1ee980-c04f-11e9-8577-3d2c88cd94b4.png)

'-s' '-t' should be 'veri' or 'vehicleID'

**Comment by chenchenver** [comment]
Hello, I have tried to set it to VeRi, but it will have a new error as follows:
![QQ图片20190816181400](https://user-images.githubusercontent.com/44572100/63161074-d16d5c80-c051-11e9-94ec-8635cbff9058.png)

When I added the '-', there were new errors as follows:
![QQ图片20190816181453](https://user-images.githubusercontent.com/44572100/63161127-e944e080-c051-11e9-8c61-2ceafa6e3a95.png)

**Comment by Jakel21** [comment]
veri not VeRi🤣
for example -s veri -t veri
| |
刘中基
|
|
邮箱：jakel21@163.com
|

签名由 网易邮箱大师 定制

On 08/16/2019 18:16, chenchenver wrote:

Hello, I have tried to set it to VeRi, but it will have a new error as follows:


When I added the '-', there were new errors as follows:

**Comment by chenchenver** [comment]
Hello, it's the same mistake after becoming veri, crying！

**Comment by chenchenver** [comment]
sorry！I made a mistake, I will try again, thank you!

**Comment by chenchenver** [comment]
Hello, I still encounter the same problem after the modification, as shown in the figure below. 
![QQ图片20190816183755](https://user-images.githubusercontent.com/44572100/63162388-fadbb780-c054-11e9-9de1-548f43417070.png)
Haw.

**Comment by Jakel21** [comment]
No need of --source
You can follow the readme
| |
刘中基
|
|
邮箱：jakel21@163.com
|

签名由 网易邮箱大师 定制

On 08/16/2019 18:38, chenchenver wrote:

Hello, I still encounter the same problem after the modification, as shown in the figure below.

Haw.

**Comment by chenchenver** [comment]
I'm sorry to bother you for so long, but I still have this problem according to what you said. I'm really sorry!
![QQ图片20190816184628](https://user-images.githubusercontent.com/44572100/63162906-5eb2b000-c056-11e9-8199-5778583637eb.png)

**Comment by Jakel21** [comment]
You should not change any thing in the code... you need to decide the source dataset and test target dataset in the terminal....


python train.py -s veri -t veri
you can search how argparse work and you will understand


| |
刘中基
|
|
邮箱：jakel21@163.com
|

签名由 网易邮箱大师 定制

On 08/16/2019 18:48, chenchenver wrote:

I'm sorry to bother you for so long, but I still have this problem according to what you said. I'm really sorry!

**Comment by chenchenver** [comment]
Thank you very much for your answers. I will carefully study and understand the following. Thank you again for your time to solve my problems! Wish you happy every day!

**Comment by Jakel21** [comment]
> Thank you very much for your answers. I will carefully study and understand the following. Thank you again for your time to solve my problems! Wish you happy every day!

i understand your problem now...
you can search something about python argparse optional arguments. '-s' '--source_names' are the same argument(they are option arguments)
happy to help you and have a nice weekend~

**Comment by chenchenver** [comment]
Tank you so so so much~~~~Have a nice weekend, too~~~

**Comment by chenchenver** [comment]
Thank~~~~~Oh my god, wrong word
